name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Build Docker images
        run: |
          docker build -t backend ./backend
          docker build -t frontend ./frontend

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your_ec2_public_ip << 'EOF'
            docker run -d -p 5000:5000 --name backend backend
            docker run -d -p 80:80 --name frontend frontend
          EOF
